/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find the Total Customers by Country
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM dwport1_gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC; 

-- Find Total Customers by Gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM dwport1_gold.dim_customers
GROUP BY gender
ORDER BY customer_gender DESC
; 

-- Find Total Products by Category
SELECT
category,
COUNT(product_key) AS total_products
FROM dwport1_gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT
category,
ROUND(AVG(cost),2) AS avg_cost
FROM dwport1_gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category?
SELECT
p.category,
ROUND(SUM(f.sales_amount), 2) AS total_revenue
FROM dwport1_gold.fact_sales AS f
LEFT JOIN dwport1_gold.dim_products AS p ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC
;

-- Find total revenue generated by each customer
SELECT
c.last_name,
c.first_name,
c.customer_key,
ROUND(SUM(f.sales_amount), 2) AS total_revenue
FROM dwport1_gold.fact_sales AS f
LEFT JOIN dwport1_gold.dim_customers AS c ON c.customer_key = f.customer_key
GROUP BY c.customer_key, c.last_name, c.first_name
ORDER BY total_revenue DESC
;

-- What is the distribution of sold items across countries?
SELECT 
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM
    dwport1_gold.fact_sales AS f
        LEFT JOIN
    dwport1_gold.dim_customers AS c ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
;



-- Totals of each category per country
SELECT 
c.country AS Country,
p.product_name AS product_name,
p.product_key AS product_key
FROM dwport1_gold.fact_sales AS f
LEFT JOIN dwport1_gold.dim_products AS p ON f.product_key = p.product_key
LEFT JOIN dwport1_gold.dim_customers AS c ON f.customer_key = c.customer_key
GROUP BY country, product_name, product_key
ORDER BY country  
;

